name: fetch-misskey

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Fetch
        run: |
          sh fetchMisskey.sh
      - name: Branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      - name: Prepare Git
        run: |
          git config --global user.email "none"
          git config --global user.name "bot"

      - name: Create fetch branch
        run: |
          git switch -c fetch
          git add src/misskey/packages
          git commit -m'fetch misskey'
          git push -f -u origin fetch

      - name: Create fetch-locales branch
        run: |
          git switch -c fetch-locales "${GIT_BRANCH_NAME}"
          git add src/misskey/locales
          git commit -m'fetch misskey-locales'
          git push -f -u origin fetch-locales

      - name: Create Pull Request
        continue-on-error: true
        run: |
          gh pr create --fill -B "${GIT_BRANCH_NAME}"
